"""Regenerate the fast PDF font pack: python -m pip install fonttools first.

Keep every character in the question bank and export UI. The original OFL font
pack remains available as a fallback for uncommon characters in personal notes.
Run this after changing the question bank; npm test checks corpus coverage.
"""
import base64
import io
import json
import re
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / "client/assets/vendor"
source = (VENDOR / "pdf-fonts.js").read_text(encoding="utf-8")
original = json.loads(source[source.index("{"):source.rindex("};") + 1])
characters = set(range(256)) | set(range(0x2000, 0x2300)) | set(range(0x3000, 0x3040)) | set(range(0xFF00, 0xFFF0))
for folder in [ROOT / "client/data/papers", ROOT / "client/data/pools", ROOT / "client/assets"]:
    for file in folder.glob("*.js"):
        text = file.read_text(encoding="utf-8")
        characters.update(map(ord, text))
        characters.update(int(x, 16) for x in re.findall(r"\\u([0-9a-fA-F]{4})", text))

def ranges(values):
    result = []
    for cp in sorted(values):
        if result and result[-1][1] + 1 == cp:
            result[-1][1] = cp
        else:
            result.append([cp, cp])
    return result

fonts, full, covered = {}, set(), set()
for filename, encoded in original.items():
    font = TTFont(io.BytesIO(base64.b64decode(encoded)))
    cmap = set(font.getBestCmap())
    full.update(cmap)
    covered.update(cmap & characters)
    options = subset.Options()
    options.flavor = "woff"
    options.recalc_timestamp = False
    options.layout_features = ["*"]
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=characters)
    sub.subset(font)
    for name in font["name"].names:
        if name.nameID in [1, 4, 6]:
            value = "ExamSerif-" + ("Bold" if "Bold" in filename else "Regular")
            name.string = value.encode(name.getEncoding())
    output = io.BytesIO()
    font.save(output)
    fonts[filename] = base64.b64encode(output.getvalue()).decode("ascii")
    print(filename, "glyphs", len(font.getBestCmap()), "bytes", len(output.getvalue()))

coverage = {"subset": ranges(covered), "full": ranges(full)}
(VENDOR / "pdf-font-coverage.js").write_text(
    "/* Generated by scripts/subset-pdf-fonts.py; Noto Serif SC, SIL OFL 1.1. */\nwindow.QB_PDF_FONT_COVERAGE="
    + json.dumps(coverage, separators=(",", ":")) + ";\n", encoding="utf-8")
(VENDOR / "pdf-fonts-lite.js").write_text(
    "/* Noto Serif SC corpus subset; SIL OFL 1.1, see NotoSerifSC-LICENSE.txt. */\nwindow.QB_PDF_LITE_FONTS="
    + json.dumps(fonts, separators=(",", ":")) + ";\n", encoding="utf-8")
